version: "3"
services:
  app1:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent1
    privileged: true

  app2:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent2
    privileged: true

  app3:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent3
    privileged: true

  app4:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent4
    privileged: true

  app5:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent5
    privileged: true
