version: "3"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    image: rameshx90/agent1:v1
    environment:
      - AZP_URL=https://dev.azure.com/thilankadileepa0082
      - AZP_TOKEN=w3oftigxvpz6lmkixfcdjmcguv3zqfdhsyjnenwhflao5ltalatq
      - AZP_AGENT_NAME=Agent1
      - AZP_POOL=local
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: rameshx90/agent2:v1
    environment:
      - AZP_URL=https://dev.azure.com/thilankadileepa0082
      - AZP_TOKEN=w3oftigxvpz6lmkixfcdjmcguv3zqfdhsyjnenwhflao5ltalatq
      - AZP_AGENT_NAME=Agent2
      - AZP_POOL=local
