version: "3"
services:
  app1:
    image: AZP-agent-image:v1
    env_file:
      - .env

  app2:
    image: AZP-agent-image:v1
    env_file:
      - .env

  app3:
    image: AZP-agent-image:v1
    env_file:
      - .env

  app4:
    image: AZP-agent-image:v1
    env_file:
      - .env

  app5:
    image: AZP-agent-image:v1
    env_file:
      - .env
