version: "3"
services:
  app1:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent1
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock:rw

  app2:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent2
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock:rw

  app3:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent3
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock:rw

  app4:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent4
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock:rw

  app5:
    image: rameshx90/azp-agents:latest
    env_file:
      - .env
    environment:
      - AZP_AGENT_NAME=az_agent5
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock:rw
